### PR TITLE
day1_q3_solution.java

### PR DESCRIPTION
**Pull request by Anushreebasics**

### CODE REVIEW

**Comment by Anushreebasics** [comment]
please merge this PR

**Comment by bh-g** [comment]
Rename the files to solution.java / solution.cpp since the day and question no. is already there.

**Comment by bh-g** [comment]
Divide this PR into 4 PRs with each having the solution to a single question.

**Comment by Nitya-Pasrija** [comment]
Closing this PR as we recommend following the new contributing rules provided in the ques segment. 
Also 4 PRs would be better :)

**Pull request closed without merging**
