### PR TITLE
Gurbranch

### PR DESCRIPTION
**Pull request by Gurn-k**
Leetcode question: Reverse words in a string by GURNOOR KAUR

Screenshot (26)
Answer accepted by leetcode

Screenshot (27)
Screenshot (28)
Screenshot (29)

### CODE REVIEW

**Comment by bh-g** [comment]
Hey Gurnoor! Please submit your code to see if it is getting accepted and code snippets are not accepted in the repo.

**Comment by Gurn-k** [comment]
Hello di!
Im able to submit the code on leetcode
Screenshot (32)

please click on the 3 dots next to the snippet and click on view file
Screenshot (30)

then please select the drop down arrow and click on github.dev
Screenshot (31)

I'm able to view the snippet this way but im not able to understand why it is not visible if we try to view the snippet directly on commit section

**Comment by bh-g** [comment]
image
I'm able to see your snippets but we're not accepting code screenshots in the repo, delete these snippets and you're good to go :)

**Comment by Gurn-k** [comment]
oh sorry i thought that we had to upload screenshots of the code also ,i have made the changes in my codespace but it is taking time to commit the changes ,can i create a new codespace and then pull request again

**Comment by bh-g** [comment]
Cool! You can make another PR then :)

**Comment by Gurn-k** [comment]
okay :)

**Comment by Gurn-k** [comment]
di i have created a new PR  #196 please check

**Pull request closed without merging**
