### PR TITLE
Search insert position cpp code added by Akansha77

### LINKED ISSUE #151: Search Insert Position
Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

You must write an algorithm with O(log n) runtime complexity. 

Example 1:

Input: nums = [1,3,5,6], target = 5
Output: 2

Example 2:

Input: nums = [1,3,5,6], target = 2
Output: 1

Example 3:

Input: nums = [1,3,5,6], target = 7
Output: 4

Constraints:

1 <= nums.length <= 104
-104 <= nums[i] <= 104
nums contains distinct values sorted in ascending order.
-104 <= target <= 104

Link : https://leetcode.com/problems/search-insert-position/description/

### PR DESCRIPTION
**Pull request by Akansha77**
Closes #151 
Search insert position cpp code added by Akansha77 @bh-g

### CODE REVIEW

**Comment by bh-g** [comment]
Hey, pls reference the issue you're working on !

**Comment by Akansha77** [comment]
dii Search insert position

**Comment by bh-g** [comment]
Add the #Issue_number in the description of your PR.

**Comment by Akansha77** [comment]
#151

**Comment by Akansha77** [comment]
dii donee

**Pull request merged**
